right:
  controller_manager:
    ros__parameters:
      update_rate: 500  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      io_and_status_controller:
        type: ur_controllers/GPIOController

      speed_scaling_state_broadcaster:
        type: ur_controllers/SpeedScalingStateBroadcaster

      force_torque_sensor_broadcaster:
        type: ur_controllers/ForceTorqueStateBroadcaster

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      scaled_joint_trajectory_controller:
        type: ur_controllers/ScaledJointTrajectoryController

      forward_velocity_controller:
        type: velocity_controllers/JointGroupVelocityController

      forward_position_controller:
        type: position_controllers/JointGroupPositionController

  speed_scaling_state_broadcaster:
    ros__parameters:
      state_publish_rate: 100.0

  force_torque_sensor_broadcaster:
    ros__parameters:
      sensor_name: right_tcp_fts_sensor
      state_interface_names:
        - right_force.x
        - right_force.y
        - right_force.z
        - right_torque.x
        - right_torque.y
        - right_torque.z
      frame_id: right_tool0
      topic_name: right_ft_data

  joint_trajectory_controller:
    ros__parameters:
      joints:
        - right_shoulder_pan_joint
        - right_shoulder_lift_joint
        - right_elbow_joint
        - right_wrist_1_joint
        - right_wrist_2_joint
        - right_wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      constraints:
        stopped_velocity_tolerance: 0.2
        goal_time: 0.0
        right_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
        right_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
        right_elbow_joint: { trajectory: 0.2, goal: 0.1 }
        right_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
        right_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
        right_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

  scaled_joint_trajectory_controller:
    ros__parameters:
      joints:
        - right_shoulder_pan_joint
        - right_shoulder_lift_joint
        - right_elbow_joint
        - right_wrist_1_joint
        - right_wrist_2_joint
        - right_wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      speed_scaling_interface_name: ""
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      constraints:
        stopped_velocity_tolerance: 0.2
        goal_time: 0.0
        right_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
        right_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
        right_elbow_joint: { trajectory: 0.2, goal: 0.1 }
        right_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
        right_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
        right_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

  forward_velocity_controller:
    ros__parameters:
      joints:
        - right_shoulder_pan_joint
        - right_shoulder_lift_joint
        - right_elbow_joint
        - right_wrist_1_joint
        - right_wrist_2_joint
        - right_wrist_3_joint
      interface_name: velocity

  forward_position_controller:
    ros__parameters:
      joints:
        - right_shoulder_pan_joint
        - right_shoulder_lift_joint
        - right_elbow_joint
        - right_wrist_1_joint
        - right_wrist_2_joint
        - right_wrist_3_joint
        