# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    wsg_left_gl_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    wsg_left_gr_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    wsg_right_gl_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    wsg_right_gr_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
right_arm_controller:
  ros__parameters:
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
wsg_left_gl_controller:
  ros__parameters:
    joints:
      - left_wsg50_base_joint_gripper_left
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
wsg_left_gr_controller:
  ros__parameters:
    joints:
      - left_wsg50_base_joint_gripper_right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
wsg_right_gl_controller:
  ros__parameters:
    joints:
      - right_wsg50_base_joint_gripper_left
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
wsg_right_gr_controller:
  ros__parameters:
    joints:
      - right_wsg50_base_joint_gripper_right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true


left_gripper_controller:
  ros__parameters:
    joints:
      - left_wsg50_base_joint_gripper_left
      - left_wsg50_base_joint_gripper_right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
right_gripper_controller:
  ros__parameters:
    joints:
      - right_wsg50_base_joint_gripper_left
      - right_wsg50_base_joint_gripper_right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true



# left_gripper_controller:
#   ros__parameters:
#     joints:
#       - left_wsg50_base_joint_gripper_left
#       - left_wsg50_base_joint_gripper_right
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     allow_nonzero_velocity_at_trajectory_end: true
#     command_topics:
#       left_wsg50_base_joint_gripper_left: /left_gripper/left_joint/command
#       left_wsg50_base_joint_gripper_right: /left_gripper/right_joint/command
