- ros_topic_name: camera/alpha_camera/color/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_color/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/alpha_camera/color/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_color/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/alpha_camera/depth/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_depth/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/alpha_camera/depth/depth_image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_depth/depth_image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/alpha_camera/depth/depth_image/points
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_depth/depth_image/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS
- ros_topic_name: camera/alpha_camera/ired/ired1/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_ired1/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/alpha_camera/ired/ired1/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_ired1/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/alpha_camera/ired/ired2/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_ired2/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/alpha_camera/ired/ired2/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_ired2/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/bravo_camera/color/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/bravo_camera_color/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/bravo_camera/color/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/bravo_camera_color/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/bravo_camera/depth/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/bravo_camera_depth/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/bravo_camera/depth/depth_image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/bravo_camera_depth/depth_image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/bravo_camera/depth/depth_image/points
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/bravo_camera_depth/depth_image/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS
- ros_topic_name: camera/bravo_camera/ired/ired1/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/bravo_camera_ired1/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/bravo_camera/ired/ired1/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/bravo_camera_ired1/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/bravo_camera/ired/ired2/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/bravo_camera_ired2/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/bravo_camera/ired/ired2/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/bravo_camera_ired2/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/charlie_camera/color/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/charlie_camera_color/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/charlie_camera/color/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/charlie_camera_color/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/charlie_camera/depth/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/charlie_camera_depth/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/charlie_camera/depth/depth_image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/charlie_camera_depth/depth_image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/charlie_camera/depth/depth_image/points
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/charlie_camera_depth/depth_image/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS
- ros_topic_name: camera/charlie_camera/ired/ired1/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/charlie_camera_ired1/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/charlie_camera/ired/ired1/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/charlie_camera_ired1/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/charlie_camera/ired/ired2/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/charlie_camera_ired2/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/charlie_camera/ired/ired2/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/charlie_camera_ired2/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/delta_camera/color/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/delta_camera_color/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/delta_camera/color/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/delta_camera_color/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/delta_camera/depth/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/delta_camera_depth/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/delta_camera/depth/depth_image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/delta_camera_depth/depth_image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/delta_camera/depth/depth_image/points
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/delta_camera_depth/depth_image/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS
- ros_topic_name: camera/delta_camera/ired/ired1/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/delta_camera_ired1/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/delta_camera/ired/ired1/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/delta_camera_ired1/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: camera/delta_camera/ired/ired2/image
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/delta_camera_ired2/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: camera/delta_camera/ired/ired2/camera_info
  gz_topic_name: /world/mantis_world/model/mantis/link/base_link/sensor/delta_camera_ired2/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
