- ros_topic_name: "/alpha_camera/color/image"
  gz_topic_name: "/world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_color/image"

  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS 

- ros_topic_name: "/alpha_camera/depth/depth_image"
  gz_topic_name: "/world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/alpha_camera/depth/depth_image/points"
  gz_topic_name: "/world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_depth/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/alpha_camera/ired/ired1/image"
  gz_topic_name: "/world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_ired1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/alpha_camera/ired/ired2/image"
  gz_topic_name: "/world/mantis_world/model/mantis/link/base_link/sensor/alpha_camera_ired2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
