- ros_topic_name: "/alpha_camera/color/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/alpha_camera_color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS 

- ros_topic_name: "/alpha_camera/depth/depth_image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/alpha_camera_depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/alpha_camera/depth/depth_image/points"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/alpha_camera_depth/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/alpha_camera/ired/ired1/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/alpha_camera_ired1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/alpha_camera/ired/ired2/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/alpha_camera_ired2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS


- ros_topic_name: "/bravo_camera/color/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/bravo_camera_color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS 

- ros_topic_name: "/bravo_camera/depth/depth_image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/bravo_camera_depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/bravo_camera/depth/depth_image/points"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/bravo_camera_depth/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/bravo_camera/ired/ired1/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/bravo_camera_ired1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/bravo_camera/ired/ired2/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/bravo_camera_ired2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS


- ros_topic_name: "/charlie_camera/color/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/charlie_camera_color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/charlie_camera/depth/depth_image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/charlie_camera_depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/charlie_camera/depth/depth_image/points"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/charlie_camera_depth/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/charlie_camera/ired/ired1/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/charlie_camera_ired1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/charlie_camera/ired/ired2/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/charlie_camera_ired2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS


- ros_topic_name: "/spare_camera/color/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/spare_camera_color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/spare_camera/depth/depth_image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/spare_camera_depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/spare_camera/depth/depth_image/points"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/spare_camera_depth/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/spare_camera/ired/ired1/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/spare_camera_ired1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/spare_camera/ired/ired2/image"
  gz_topic_name: "/world/workbench_world/model/dual_ur/link/base_link/sensor/spare_camera_ired2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS